### PR TITLE
lab4

### PR DESCRIPTION
**Pull request by lubakach**
Lab4

### CODE REVIEW

**Comment by lubakach** [comment]
I was lazy, so i didnt add questions to game KsisQuiz) but u can make ur own game. At the result-page there is no buttons, but u can click on pic.House at the top to retun to the start
Hope it helps

**Review by gmltA — CHANGES_REQUESTED** [review]
Very interesting.

image

**Comment by lubakach** [comment]
Oh, https://lubakach.github.io/Quiz/CandyQuizJS/#start

**Review by gmltA — CHANGES_REQUESTED** [review]
Aaand where's the 'online' part from topic 'Onine quiz'?

**Comment by lubakach** [comment]
I didn't see that, maybe I just forgot about it, maybe it's okay to pass like this? because I need to change everything even design
And I don't have time for that 
Pleeeeeeaaaase 😭😢

**Review by gmltA — CHANGES_REQUESTED** [review]
I receive 404 on your link right now. Can you update the deployment?

**Review by gmltA — CHANGES_REQUESTED** [review]
Okay I can accept your project without online player interaction, but you will need to connect your app to firebase and store your quiz data and statistics there.

Use this PR for further development.

**Comment by lubakach** [comment]
Hah, yes, i have the same problem yesterday, just clean cache

**Comment by lubakach** [comment]
I have another pull request lab5

**Comment by lubakach** [comment]
https://lubakach.github.io/Quiz/#start
sorry, this is working link

**Review by gmltA — APPROVED** [review]
My offer stays the same: <kbd>9</kbd> for this milestone and I expect you to add remote DB to your project to get the final mark.

**Comment by lubakach** [comment]
I already did that 
You can see my final project at pull request lab5

**Comment by lubakach** [comment]
https://lubakach.github.io/Quiz/CandyQuizJS//#start

**Pull request merged**
